version: '3.8'

services:
  ui:
    build:
      context: .
      target: ui-build
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      target: server-build
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

