name: Build and Deploy React-Node.js App with CapRover

on: [push, pull_request]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx for advanced build options
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Log in to GitHub Container Registry (or another registry if configured)
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # Step 5: Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/react-node-app:${{ github.sha }}

    # Step 6: Deploy the Docker Image to CapRover
    - name: Deploy Image to CapRover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: "${{ secrets.CAPROVER_SERVER }}"
        app: "${{ secrets.APP_NAME }}"
        token: "${{ secrets.CAPROVER_TOKEN }}"
        image: ghcr.io/${{ github.repository_owner }}/react-node-app:${{ github.sha }}

