name: Build and Deploy React-Node.js App with CapRover

on: [push, pull_request]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/react-node-app:${{ github.sha }}

      # Add debug step
      - name: Debug Information
        run: |
          echo "Server URL: ${{ secrets.APP_SERVER }}"
          echo "App Name: ${{ secrets.APP_NAME }}"
          echo "Image: ghcr.io/${{ github.repository_owner }}/react-node-app:${{ github.sha }}"

      - name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0  # Only use temporarily for testing
        with:
          server: '${{ secrets.APP_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          image: ghcr.io/${{ github.repository_owner }}/react-node-app:${{ github.sha }}
